### ISSUE TITLE
CUDA isn't detected from Docker container on AWS

### ISSUE THREAD

**Issue by fw-ashmistry** [Deep-MI/FastSurfer#352]
## Question/Support Request
CUDA/GPU isn't detected from the docker container off my host. My question is, do the docker CUDA drivers have to match the version of CUDA on the host as well? According to the [yml file](https://github.com/Deep-MI/FastSurfer/blob/v2.1.1/fastsurfer_env_gpu.yml)  the CUDA toolkit (inside the container) is cudatoolkit=11.3. Running nvidia-smi from host below tells me the host is version 11.4. `nvidia-smi` is not found inside the container so I can't run it off from there. So then I separately installed it and got `Failed to initialize NVML: Unknown Error` when I ran `nvidia-smi` from my container.  Any help/clarification on this would be really appreciated.

## Screenshots

```
Running nvidia-smi  off my host gives me:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   44C    P0    25W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by m-reuter** [comment]
Hi, what is your host operating system? Also what is the command you used to start the docker image?

**Comment by fw-ashmistry** [comment]
Amazon Linux 2 is the host OS (g4dn.xlarge instance in case you are curious) Command used: `docker run -v /path_to_input/:/input:ro -v /path_to_output:/output -t my_fastsurfer:gpu run.py my_arg1 my_arg2`

`run.py` runs `run_prediction.py` and `recon-surf.sh`

**Comment by m-reuter** [comment]
First thing to try is to run according to our documentation on our own image: 
```
docker run --gpus all \
           -v /home/user/my_mri_data:/data \
           -v /home/user/my_fastsurfer_analysis:/output \
           -v /home/user/my_fs_license_dir:/fs_license \
           --rm --user $(id -u):$(id -g) \
           deepmi/fastsurfer:latest \
           *fastsurfer-flags*
```

Especially you need to pass the `--gpus all` to make sure it finds the gpu inside docker. Once that works, you can start playing around with your own images.

**Comment by fw-ashmistry** [comment]
This is my output. Still defaults to cpu. The `cuda available False` that you see in the log below is from torch, `torch.cuda.is_available()`

```
cuda available False
INFO - Calling...
/venv/bin/python /fastsurfer/FastSurferCNN/run_prediction.py --t1 /input/input_t1.nii.gz --sd /output --seg_log /output/segmentation.log --allow_root
[INFO: run_prediction.py:  392]: Checking or downloading default checkpoints ...
[INFO: common.py:  102]: Using device: cpu
[INFO: run_prediction.py:  133]: Running view aggregation on cpu
etc etc...
```

**Comment by m-reuter** [comment]
Could have to do with the cloud instances. Try to get a minimal docker with GPU running ( eg Nvidia smi) when that works, one with torch and run the is_available. I think it is more a setup thing rather than an issue with our containers which work everywhere else.

**Comment by fw-ashmistry** [comment]
Gotcha thanks. I did switch the base to nvcr.io/nvidia/pytorch:22.08-py3 from ubuntu 20.04 and it worked. It's just that the 2.1.1 image is a lot smaller than pytorch's. You think it could be different version of cudatoolkit? Cuda on host is 11.4, while 2.1.1 is 11.3. 
But thanks for your help!

**Comment by m-reuter** [comment]
Thanks for reporting the workaround. Not sure why this happens. We also have different cuda versions locally than what is in the container and it works here. Would be good to find out what it is exactly, so that we can create containers that work everywhere.

**Comment by m-reuter** [comment]
dkuegler pointed out to me that just adding this:
 ```ENV NVIDIA_DRIVER_CAPABILITIES=all ```
to the docker file and building might be sufficient. See
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-gpu.html

> When you build a container image that doesn't use the NVIDIA/CUDA base images, you must set the NVIDIA_DRIVER_CAPABILITIES container runtime variable to one of the following values:
    utility, compute
    all
For information about how to set the variable, see [Controlling the NVIDIA Container Runtime](https://sarus.readthedocs.io/en/stable/user/custom-cuda-images.html#controlling-the-nvidia-container-runtime) on the NVIDIA website.

Not tested yet.

**Comment by fw-ashmistry** [comment]
cuda was detected and did the seg in under 1 min! These were the first few lines of my Dockerfile

```
FROM deepmi/fastsurfer:gpu-v2.1.1

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES=all
ENV NVIDIA_REQUIRE_CUDA "cuda>=8.0"

etc..
```
Thanks @dkuegler @m-reuter !

**Comment by dkuegler** [comment]
Thanks @ashmistry36! 

Can you confirm you did not have to specify `-e NVIDIA_DRIVER_CAPABILITIES=all` on the command line in the docker run command any more? And also, can you share what exactly you had to set as environment variables? We can bake that into future fastsurfer images then.

**Comment by fw-ashmistry** [comment]
Cool! 
I did not have to specify that on the command line. I shared those 3 environment variables above in the Dockerfile. I copied that directly https://sarus.readthedocs.io/en/stable/user/custom-cuda-images.html#controlling-the-nvidia-container-runtime

**Comment by dkuegler** [comment]
#215 will bake these variables into the default images
