### ISSUE TITLE
Unable to run fastsurfer on cuda on Geforce 3070x with 8 GB

### ISSUE THREAD

**Issue by knutj** [Deep-MI/FastSurfer#53]
python3.8 eval.py --in_name /home/knutjb/subjects/bert_fast/mri/orig/001.mgz --out_name /home/knutjb/subjects//bert_fast/mri/aparc.DKTatlas+aseg.deep.mgz --order 1 --network_sagittal_path /home/knutjb/sources/FastSurfer/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_axial_path /home/knutjb/sources/FastSurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_coronal_path /home/knutjb/sources/FastSurfer/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --batch_size 8 --simple_run --run_viewagg_on check
Reading volume /home/knutjb/subjects/bert_fast/mri/orig/001.mgz
Cuda available: True, # Available GPUS: 1, Cuda user disabled (--no_cuda flag): False, --> Using device: cuda
Loading Axial
Successfully loaded Image from /home/knutjb/subjects/bert_fast/mri/orig/001.mgz
Loading Axial Net from /home/knutjb/sources/FastSurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl
Axial model loaded.
Traceback (most recent call last):
  File "eval.py", line 462, in <module>
    fastsurfercnn(options.iname, options.oname, use_cuda, small_gpu, logger, options)
  File "eval.py", line 308, in fastsurfercnn
    pred_prob = run_network(img_filename,
  File "eval.py", line 211, in run_network
    temp = model(images_batch)
  File "/home/knutjb/python3.8/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/extra_space2/sources/FastSurfer/FastSurferCNN/models/networks.py", line 69, in forward
    encoder_output1, skip_encoder_1, indices_1 = self.encode1.forward(x)
  File "/extra_space2/sources/FastSurfer/FastSurferCNN/models/sub_module.py", line 263, in forward
    out_block = super(CompetitiveEncoderBlockInput, self).forward(x)  # To be concatenated as Skip Connection
  File "/extra_space2/sources/FastSurfer/FastSurferCNN/models/sub_module.py", line 201, in forward
    x2 = torch.cat((x2_bn, x1_bn), dim=4)  # Concatenating along the 5th dimension
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 7.79 GiB total capacity; 5.49 GiB already allocated; 269.06 MiB free; 5.49 GiB reserved in total by PyTorch)
(python3.8) knutjb@knut:~/sources/FastSurfer$ ./run_fastsurfer_kjb.sh --t1 ~/subjects/bert_fast/mri/orig.mgz --sid bert_fast --sd ~/subjects/ --parallel --threads 4 --no_cuda
Setting ENV variable FASTSURFER_HOME to current working directory /home/knutjb/sources/FastSurfer. 
Change via enviroment to location of your choice if this is undesired (export FASTSURFER_HOME=/dir/to/FastSurfer)

**Comment by m-reuter** [comment]
Not sure, looks like you are already using 5.5GiB ? 

Anyway, you can try to reduce the batch size (there is a flag for this, default is 8). And it also seems you need to set your FREESURFER_HOME environment variable to where your FreeSurfer is installed (see FreeSurfer documentation, for how to source set it up and source it by calling their setup script, basically :

$ export FREESURFER_HOME=$HOME/freesurfer
$ source $FREESURFER_HOME/SetUpFreeSurfer.sh
 
see https://surfer.nmr.mgh.harvard.edu/fswiki//FS7_linux

**Comment by LeHenschel** [comment]
Hey,

the problem is the batch size as Martin suggested above. For a 8GB graphic card, this needs to be lowered to 4 (I just tested it on a GeForce RTX 2080 with 8GB). For the command, you simply need to add the flag: **--batch 4** (for run_fastsurfer.sh; use --batch_size 4 for eval.py)

```bash
# Local install run_fastsurfer.sh
./run_fastsurfer.sh --t1 /home/knutjb/subjects/bert_fast/mri/orig/001.mgz \
                    --sid bert_fast --sd /home/knutjb/subjects \
                    --batch 4

# Local install eval.py
python3.8 eval.py --in_name /home/knutjb/subjects/bert_fast/mri/orig/001.mgz \
                  --out_name /home/knutjb/subjects//bert_fast/mri/aparc.DKTatlas+aseg.deep.mgz \
                  --simple_run --batch_size 4


# Docker (segmentation only)
docker run --gpus all -v /home/knutjb/subjects:/data --rm -it --user $(id -u):$(id -g) \
deepmi/fastsurfer:gpu-beta --t1 /data/bert_fast/mri/orig/001.mgz \
                           --sid bert_fast --sd /data \
                           --batch 4 --seg_only

# Docker (full pipeline)
docker run --gpus all -v /home/knutjb/subjects:/data --rm -it --user $(id -u):$(id -g) \
deepmi/fastsurfer:gpu-beta --t1 /data/bert_fast/mri/orig/001.mgz \
                           --sid bert_fast --sd /data \
                           --batch 4

# Segmentation Docker
docker run --gpus all -v /home/knutjb/subjects:/data --rm -it --user $(id -u):$(id -g) \
deepmi/fastsurfer:segonly-gpu-beta --in_name /data/bert_fast/mri/orig/001.mgz \
                                   --out_name /data/bert_fast/mri/aparc.DKTatlas+aseg.deep.mgz \
                                   --simple_run --batch_size 4
```
Best,
Leonie

**Comment by knutj** [comment]
I am able to get running longer with batch size 1. I have cuda 11.3 along with pytorch 1.9 using Python 3.8. I will try with Python 3.6

**Comment by knutj** [comment]
I was able to run fastsurfer by using this option --run_viewagg_on cpu and batch at 8.

**Comment by knutj** [comment]
Resolved

**Comment by greydongilmore** [comment]
Thank you!! I kept receiving an out of CUDA memory error on my 2080Ti. Changing the batch size and thread number didn't help. The solution was to add the `--run_viewagg_on cpu` flag
