### ISSUE TITLE
cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by 0rC0** [Deep-MI/FastSurfer#68]
Hello,

and thank you for sharing the code :-)

I'm having an issue with the GPU version of the Docker container.

After building the Docker container, I run a `bash` script iterating the subjects with this command:

```
docker run --gpus all\
		 -v $dev_path:/data \
		 -v $dev_path:/output \
		 -v ${fs_lic}:/fs60 \
		 --rm --user $uid fastsurfer:gpu \
		 --fs_license /fs60/license.txt \
		 --t1 /data/$i/orig.mgz \
		 --sid $i --sd /output \
		 --parallel --seg_only
```

and this is my output:

```
Fri Oct  1 14:30:10 UTC 2021

/fastsurfer/FastSurferCNN /fastsurfer
python3.6 eval.py --in_name /data/sub-XXX/orig.mgz --out_name /output/sub-XXX/mri/aparc.DKTatlas+aseg.deep.mgz --order 1 --network_sagittal_path /fastsurfer/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_axial_path /fastsurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_coronal_path /fastsurfer/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --batch_size 8 --simple_run --run_viewagg_on check
Reading volume /data/sub-XXX/orig.mgz
Conforming image to UCHAR, RAS orientation, and 1mm isotropic voxels
Input:    min: 0.0  max: 353.0
rescale:  min: 0.0  max: 264.397  scale: 0.9644587495319539
Output:   min: 0.0  max: 255.0
Cuda available: True, # Available GPUS: 1, Cuda user disabled (--no_cuda flag): False, --> Using device: cuda
Loading Axial
Successfully loaded Image from /data/sub-XXX/orig.mgz
Loading Axial Net from /fastsurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl
Axial model loaded.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THC/THCGeneral.cpp line=371 error=48 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "eval.py", line 462, in <module>
    fastsurfercnn(options.iname, options.oname, use_cuda, small_gpu, logger, options)
  File "eval.py", line 311, in fastsurfercnn
    params_model, model, logger, gpu_small)
  File "eval.py", line 211, in run_network
    temp = model(images_batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/fastsurfer/FastSurferCNN/models/networks.py", line 69, in forward
    encoder_output1, skip_encoder_1, indices_1 = self.encode1.forward(x)
  File "/fastsurfer/FastSurferCNN/models/sub_module.py", line 263, in forward
    out_block = super(CompetitiveEncoderBlockInput, self).forward(x)  # To be concatenated as Skip Connection
  File "/fastsurfer/FastSurferCNN/models/sub_module.py", line 191, in forward
    x0 = self.conv0(x0_bn)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

```
The CPU version works without problems as well as the GPU container running without `--gpus all` (using the CPU). I'm using a `GeForce RTX 3090` with 24Gb Memory.

If you need more informations, just ask :-).

Thank you in advance!
BW

**Comment by 0rC0** [comment]
Hello Leonie,

thank you, it worked!

Best,
Andrea

**Comment by m-reuter** [comment]
One thing: this way you are running a currently unsupported version as we have not tested this setup. In case you run into any problems, you should mention this setup when posting issues. Hopefully we can upgrade everything to newer versions soon on our end.
